#
# valet.sh | exec
#
# @author: "Philipp Dittert"
# @command: "exec"
# @platform: macOS Ubuntu
# @description: "Execute commands in the project environment (PHP, MySQL)"
# @usage: "valet.sh exec <action>"
# @help:
#
# All commands will be executed in the project environment with access to
# PHP, MySQL, and other configured services.
#
# Examples:
#   valet.sh exec php -v
#   valet.sh exec mysql -u root
#   valet.sh exec composer install
#
---

- name: "exec"
  hosts: local
  gather_facts: True
  vars:
    valet_action: "{{ cli.args[0] | default() }}"
    valet_current_path: "{{ lookup('env','OLDPWD') }}"
    valet_action_target: "{{ cli.args[1] | default() }}"
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "[sudo] Password"
      private: yes
  roles:
    - sudo-permission-check
    - valet-exec