#
# valet.sh | xps-setup
#
# Configure a Dell XPS Notebook according to model/family
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @author: "Florian Schmid"
# @command: "xps-setup"
# @description: "Configure Dell XPS Notebook for development"
# @usage: "valet.sh xps-setup"
# @help:
#
# Configures a Dell XPS notebook with required development tools and settings
# according to the machine model and family specifications.
---
- name: "xps-setup"
  hosts: local
  gather_facts: True
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "[sudo] Password"
      private: yes
  roles:
    - sudo-permission-check
    - dell-xps
